2023-06-18 15:41:56,937        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: anonymous
2023-06-18 15:41:58,964        CRITICAL     client.py                 Не удалось подключиться к серверу 127.0.0.1:8079, конечный компьютер отверг запрос на подключение.
2023-06-18 15:42:53,370        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_2
2023-06-18 15:42:53,371        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_1
2023-06-18 15:42:53,372        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_2
2023-06-18 15:42:53,374        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_3
2023-06-18 15:42:53,377        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_3
2023-06-18 15:42:53,403        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_3',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,405        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=420, family=2, type=1, proto=0, laddr=('127.0.0.1', 50200), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687092173.3775995, 'user': {'account_name': 'test_3'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,405        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_1',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,406        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=336, family=2, type=1, proto=0, laddr=('127.0.0.1', 50198), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687092173.3716154, 'user': {'account_name': 'test_1'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,408        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_2',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,409        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=416, family=2, type=1, proto=0, laddr=('127.0.0.1', 50199), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687092173.3726137, 'user': {'account_name': 'test_2'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,907        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=336, family=2, type=1, proto=0, laddr=('127.0.0.1', 50198), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,907        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 15:42:53,908        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,909        INFO         client.py                 Принят ответ от сервера 200 : OK
2023-06-18 15:42:53,910        DEBUG        client.py                 Запущены процессы
2023-06-18 15:42:53,911        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=416, family=2, type=1, proto=0, laddr=('127.0.0.1', 50199), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,911        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 15:42:53,912        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,912        INFO         client.py                 Принят ответ от сервера 200 : OK
2023-06-18 15:42:53,913        DEBUG        client.py                 Запущены процессы
2023-06-18 15:42:53,915        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=420, family=2, type=1, proto=0, laddr=('127.0.0.1', 50200), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,916        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 15:42:53,917        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 15:42:53,917        INFO         client.py                 Принят ответ от сервера 200 : OK
2023-06-18 15:42:53,918        DEBUG        client.py                 Запущены процессы
2023-06-18 15:43:36,538        DEBUG        client.py                 Сформирован словарь сообщения: {'action': 'message', 'from': 'test_3', 'to': 'test_2', 'time': 1687092216.5385835, 'mess_text': 'Hello'}
2023-06-18 15:43:36,544        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=420, family=2, type=1, proto=0, laddr=('127.0.0.1', 50200), raddr=('127.0.0.1', 8079)>, {'action': 'message', 'from': 'test_3', 'to': 'test_2', 'time': 1687092216.5385835, 'mess_text': 'Hello'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции create_message
2023-06-18 15:43:36,544        INFO         client.py                 Отправлено сообщение для пользователя test_2
2023-06-18 15:43:36,546        DEBUG        client.py                 Была вызвана функция create_message c параметрами (<socket.socket fd=420, family=2, type=1, proto=0, laddr=('127.0.0.1', 50200), raddr=('127.0.0.1', 8079)>, 'test_3'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 15:43:36,703        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=416, family=2, type=1, proto=0, laddr=('127.0.0.1', 50199), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции message_from_server
2023-06-18 15:43:36,703        INFO         client.py                 Получено сообщение от пользователя test_3:
Hello
2023-06-18 15:44:16,340        DEBUG        client.py                 Была вызвана функция create_exit_message c параметрами ('test_2',), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 15:44:16,342        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=416, family=2, type=1, proto=0, laddr=('127.0.0.1', 50199), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687092256.3393123, 'account_name': 'test_2', 'mess_text': 'Пользователь test_2 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 15:44:16,343        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 15:44:16,783        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 15:44:16,785        DEBUG        threading.py              Была вызвана функция message_from_server c параметрами (<socket.socket fd=416, family=2, type=1, proto=0, laddr=('127.0.0.1', 50199), raddr=('127.0.0.1', 8079)>, 'test_2'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 15:44:16,844        DEBUG        threading.py              Была вызвана функция user_interactive c параметрами (<socket.socket fd=416, family=2, type=1, proto=0, laddr=('127.0.0.1', 50199), raddr=('127.0.0.1', 8079)>, 'test_2'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 15:44:23,452        DEBUG        client.py                 Была вызвана функция create_exit_message c параметрами ('test_3',), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 15:44:23,454        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=420, family=2, type=1, proto=0, laddr=('127.0.0.1', 50200), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687092263.4512267, 'account_name': 'test_3', 'mess_text': 'Пользователь test_3 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 15:44:23,454        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 15:44:23,921        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 15:44:23,923        DEBUG        threading.py              Была вызвана функция message_from_server c параметрами (<socket.socket fd=420, family=2, type=1, proto=0, laddr=('127.0.0.1', 50200), raddr=('127.0.0.1', 8079)>, 'test_3'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 15:44:29,605        DEBUG        client.py                 Была вызвана функция create_exit_message c параметрами ('test_1',), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 15:44:29,606        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=336, family=2, type=1, proto=0, laddr=('127.0.0.1', 50198), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687092269.6031377, 'account_name': 'test_1', 'mess_text': 'Пользователь test_1 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 15:44:29,607        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 15:44:30,039        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 15:44:30,041        DEBUG        threading.py              Была вызвана функция message_from_server c параметрами (<socket.socket fd=336, family=2, type=1, proto=0, laddr=('127.0.0.1', 50198), raddr=('127.0.0.1', 8079)>, 'test_1'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 15:44:30,109        DEBUG        threading.py              Была вызвана функция user_interactive c параметрами (<socket.socket fd=336, family=2, type=1, proto=0, laddr=('127.0.0.1', 50198), raddr=('127.0.0.1', 8079)>, 'test_1'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 16:24:36,896        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_3
2023-06-18 16:24:36,908        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_2
2023-06-18 16:24:36,922        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_1
2023-06-18 16:24:37,407        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_3
2023-06-18 16:24:37,424        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_2
2023-06-18 16:24:37,426        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_3',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,428        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=388, family=2, type=1, proto=0, laddr=('127.0.0.1', 50418), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687094677.4079187, 'user': {'account_name': 'test_3'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,438        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_1
2023-06-18 16:24:37,441        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_2',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,443        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=360, family=2, type=1, proto=0, laddr=('127.0.0.1', 50419), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687094677.4240186, 'user': {'account_name': 'test_2'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,457        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=388, family=2, type=1, proto=0, laddr=('127.0.0.1', 50418), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,458        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 16:24:37,458        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_1',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,459        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,459        INFO         client.py                 Принят ответ от сервера 200 : OK
2023-06-18 16:24:37,460        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=312, family=2, type=1, proto=0, laddr=('127.0.0.1', 50420), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687094677.4380956, 'user': {'account_name': 'test_1'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,460        DEBUG        client.py                 Запущены процессы
2023-06-18 16:24:37,968        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=360, family=2, type=1, proto=0, laddr=('127.0.0.1', 50419), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,968        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 16:24:37,969        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,970        INFO         client.py                 Принят ответ от сервера 200 : OK
2023-06-18 16:24:37,971        DEBUG        client.py                 Запущены процессы
2023-06-18 16:24:37,971        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=312, family=2, type=1, proto=0, laddr=('127.0.0.1', 50420), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,971        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 16:24:37,972        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 16:24:37,973        INFO         client.py                 Принят ответ от сервера 200 : OK
2023-06-18 16:24:37,974        DEBUG        client.py                 Запущены процессы
2023-06-18 16:25:22,515        DEBUG        client.py                 Сформирован словарь сообщения: {'action': 'message', 'from': 'test_1', 'to': 'test_3', 'time': 1687094722.5156102, 'mess_text': 'Hello World'}
2023-06-18 16:25:22,519        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=312, family=2, type=1, proto=0, laddr=('127.0.0.1', 50420), raddr=('127.0.0.1', 8079)>, {'action': 'message', 'from': 'test_1', 'to': 'test_3', 'time': 1687094722.5156102, 'mess_text': 'Hello World'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции create_message
2023-06-18 16:25:22,519        INFO         client.py                 Отправлено сообщение для пользователя test_3
2023-06-18 16:25:22,521        DEBUG        client.py                 Была вызвана функция create_message c параметрами (<socket.socket fd=312, family=2, type=1, proto=0, laddr=('127.0.0.1', 50420), raddr=('127.0.0.1', 8079)>, 'test_1'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 16:25:22,703        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=388, family=2, type=1, proto=0, laddr=('127.0.0.1', 50418), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции message_from_server
2023-06-18 16:25:22,703        INFO         client.py                 Получено сообщение от пользователя test_1:
Hello World
2023-06-18 16:25:33,637        DEBUG        client.py                 Была вызвана функция create_exit_message c параметрами ('test_3',), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 16:25:33,639        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=388, family=2, type=1, proto=0, laddr=('127.0.0.1', 50418), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687094733.636207, 'account_name': 'test_3', 'mess_text': 'Пользователь test_3 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 16:25:33,639        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 16:25:33,932        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 16:25:33,934        DEBUG        threading.py              Была вызвана функция message_from_server c параметрами (<socket.socket fd=388, family=2, type=1, proto=0, laddr=('127.0.0.1', 50418), raddr=('127.0.0.1', 8079)>, 'test_3'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 16:25:34,141        DEBUG        threading.py              Была вызвана функция user_interactive c параметрами (<socket.socket fd=388, family=2, type=1, proto=0, laddr=('127.0.0.1', 50418), raddr=('127.0.0.1', 8079)>, 'test_3'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 16:25:41,885        DEBUG        client.py                 Была вызвана функция create_exit_message c параметрами ('test_2',), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 16:25:41,886        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=360, family=2, type=1, proto=0, laddr=('127.0.0.1', 50419), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687094741.883918, 'account_name': 'test_2', 'mess_text': 'Пользователь test_2 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 16:25:41,887        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 16:25:42,078        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 16:25:42,080        DEBUG        threading.py              Была вызвана функция message_from_server c параметрами (<socket.socket fd=360, family=2, type=1, proto=0, laddr=('127.0.0.1', 50419), raddr=('127.0.0.1', 8079)>, 'test_2'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 16:25:42,389        DEBUG        threading.py              Была вызвана функция user_interactive c параметрами (<socket.socket fd=360, family=2, type=1, proto=0, laddr=('127.0.0.1', 50419), raddr=('127.0.0.1', 8079)>, 'test_2'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 16:25:48,509        DEBUG        client.py                 Была вызвана функция create_exit_message c параметрами ('test_1',), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 16:25:48,511        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=312, family=2, type=1, proto=0, laddr=('127.0.0.1', 50420), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687094748.508022, 'account_name': 'test_1', 'mess_text': 'Пользователь test_1 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 16:25:48,511        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 16:25:48,735        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 16:25:48,737        DEBUG        threading.py              Была вызвана функция message_from_server c параметрами (<socket.socket fd=312, family=2, type=1, proto=0, laddr=('127.0.0.1', 50420), raddr=('127.0.0.1', 8079)>, 'test_1'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 19:09:26,471        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_1
2023-06-18 19:09:26,480        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_2
2023-06-18 19:09:26,499        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_3
2023-06-18 19:09:28,495        CRITICAL     client.py                 Не удалось подключиться к серверу 127.0.0.1:8079, конечный компьютер отверг запрос на подключение.
2023-06-18 19:09:28,510        CRITICAL     client.py                 Не удалось подключиться к серверу 127.0.0.1:8079, конечный компьютер отверг запрос на подключение.
2023-06-18 19:09:28,526        CRITICAL     client.py                 Не удалось подключиться к серверу 127.0.0.1:8079, конечный компьютер отверг запрос на подключение.
2023-06-18 19:38:48,066        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_1
2023-06-18 19:38:48,129        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_3
2023-06-18 19:38:50,097        CRITICAL     client.py                 Не удалось подключиться к серверу 127.0.0.1:8079, конечный компьютер отверг запрос на подключение.
2023-06-18 19:38:50,145        CRITICAL     client.py                 Не удалось подключиться к серверу 127.0.0.1:8079, конечный компьютер отверг запрос на подключение.
2023-06-18 19:45:26,887        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_1
2023-06-18 19:45:26,889        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_1
2023-06-18 19:45:26,896        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_2
2023-06-18 19:45:26,897        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_2
2023-06-18 19:45:26,910        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_1',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:26,911        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=384, family=2, type=1, proto=0, laddr=('127.0.0.1', 51127), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687106726.8898008, 'user': {'account_name': 'test_1'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:26,919        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_2',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:26,920        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=408, family=2, type=1, proto=0, laddr=('127.0.0.1', 51128), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687106726.897781, 'user': {'account_name': 'test_2'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:26,922        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_3
2023-06-18 19:45:26,923        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_3
2023-06-18 19:45:26,938        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_3',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:26,940        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=296, family=2, type=1, proto=0, laddr=('127.0.0.1', 51129), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687106726.9237528, 'user': {'account_name': 'test_3'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:26,942        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=384, family=2, type=1, proto=0, laddr=('127.0.0.1', 51127), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:26,943        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 19:45:26,947        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:26,952        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=408, family=2, type=1, proto=0, laddr=('127.0.0.1', 51128), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:26,952        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 19:45:26,954        INFO         client.py                 Принят ответ от сервера 200 : OK
2023-06-18 19:45:26,954        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:26,956        INFO         client.py                 Принят ответ от сервера 200 : OK
2023-06-18 19:45:26,957        DEBUG        client.py                 Запущены процессы
2023-06-18 19:45:26,957        DEBUG        client.py                 Запущены процессы
2023-06-18 19:45:27,472        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=296, family=2, type=1, proto=0, laddr=('127.0.0.1', 51129), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:27,472        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 19:45:27,473        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 19:45:27,487        INFO         client.py                 Принят ответ от сервера 200 : OK
2023-06-18 19:45:27,488        DEBUG        client.py                 Запущены процессы
2023-06-18 19:46:07,830        DEBUG        client.py                 Сформирован словарь сообщения: {'action': 'message', 'from': 'test_1', 'to': 'test_3', 'time': 1687106767.830598, 'mess_text': 'My friends'}
2023-06-18 19:46:07,833        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=384, family=2, type=1, proto=0, laddr=('127.0.0.1', 51127), raddr=('127.0.0.1', 8079)>, {'action': 'message', 'from': 'test_1', 'to': 'test_3', 'time': 1687106767.830598, 'mess_text': 'My friends'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции create_message
2023-06-18 19:46:07,834        INFO         client.py                 Отправлено сообщение для пользователя test_3
2023-06-18 19:46:07,835        DEBUG        client.py                 Была вызвана функция create_message c параметрами (<socket.socket fd=384, family=2, type=1, proto=0, laddr=('127.0.0.1', 51127), raddr=('127.0.0.1', 8079)>, 'test_1'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 19:46:08,248        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=296, family=2, type=1, proto=0, laddr=('127.0.0.1', 51129), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции message_from_server
2023-06-18 19:46:08,250        INFO         client.py                 Получено сообщение от пользователя test_1:
My friends
2023-06-18 19:46:36,168        DEBUG        client.py                 Была вызвана функция create_exit_message c параметрами ('test_1',), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 19:46:36,170        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=384, family=2, type=1, proto=0, laddr=('127.0.0.1', 51127), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687106796.1666088, 'account_name': 'test_1', 'mess_text': 'Пользователь test_1 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 19:46:36,171        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 19:46:36,215        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 19:46:36,216        DEBUG        threading.py              Была вызвана функция message_from_server c параметрами (<socket.socket fd=384, family=2, type=1, proto=0, laddr=('127.0.0.1', 51127), raddr=('127.0.0.1', 8079)>, 'test_1'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 19:46:36,672        DEBUG        threading.py              Была вызвана функция user_interactive c параметрами (<socket.socket fd=384, family=2, type=1, proto=0, laddr=('127.0.0.1', 51127), raddr=('127.0.0.1', 8079)>, 'test_1'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 19:46:42,880        DEBUG        client.py                 Была вызвана функция create_exit_message c параметрами ('test_3',), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 19:46:42,882        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=296, family=2, type=1, proto=0, laddr=('127.0.0.1', 51129), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687106802.8793113, 'account_name': 'test_3', 'mess_text': 'Пользователь test_3 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 19:46:42,883        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 19:46:43,322        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 19:46:43,323        DEBUG        threading.py              Была вызвана функция message_from_server c параметрами (<socket.socket fd=296, family=2, type=1, proto=0, laddr=('127.0.0.1', 51129), raddr=('127.0.0.1', 8079)>, 'test_3'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 19:46:43,384        DEBUG        threading.py              Была вызвана функция user_interactive c параметрами (<socket.socket fd=296, family=2, type=1, proto=0, laddr=('127.0.0.1', 51129), raddr=('127.0.0.1', 8079)>, 'test_3'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 19:46:49,945        DEBUG        client.py                 Была вызвана функция create_exit_message c параметрами ('test_2',), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 19:46:49,946        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=408, family=2, type=1, proto=0, laddr=('127.0.0.1', 51128), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687106809.9426124, 'account_name': 'test_2', 'mess_text': 'Пользователь test_2 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive
2023-06-18 19:46:49,947        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 19:46:49,954        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 19:46:49,955        DEBUG        threading.py              Была вызвана функция message_from_server c параметрами (<socket.socket fd=408, family=2, type=1, proto=0, laddr=('127.0.0.1', 51128), raddr=('127.0.0.1', 8079)>, 'test_2'), {}. Вызов из модуля __main__. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 21:06:30,143        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_1
2023-06-18 21:06:30,144        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_1
2023-06-18 21:06:30,144        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_2
2023-06-18 21:06:30,144        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_3
2023-06-18 21:06:30,145        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_3
2023-06-18 21:06:30,166        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_2',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 21:06:30,167        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=320, family=2, type=1, proto=0, laddr=('127.0.0.1', 51306), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687111590.145506, 'user': {'account_name': 'test_2'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:06:30,167        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_3',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 21:06:30,168        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=332, family=2, type=1, proto=0, laddr=('127.0.0.1', 51305), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687111590.1445096, 'user': {'account_name': 'test_1'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:06:30,168        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=396, family=2, type=1, proto=0, laddr=('127.0.0.1', 51307), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687111590.145506, 'user': {'account_name': 'test_3'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:06:30,673        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=332, family=2, type=1, proto=0, laddr=('127.0.0.1', 51305), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:06:30,673        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 21:06:30,674        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 21:06:30,674        INFO         client.py                 Установлено соединение с сервером.Принят ответ от сервера 200 : OK
2023-06-18 21:06:30,677        DEBUG        client.py                 Запущены процессы
2023-06-18 21:06:30,677        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=320, family=2, type=1, proto=0, laddr=('127.0.0.1', 51306), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:06:30,677        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 21:06:30,678        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 21:06:30,679        INFO         client.py                 Установлено соединение с сервером.Принят ответ от сервера 200 : OK
2023-06-18 21:06:30,680        DEBUG        client.py                 Запущены процессы
2023-06-18 21:06:30,681        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=396, family=2, type=1, proto=0, laddr=('127.0.0.1', 51307), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:06:30,681        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 21:06:30,682        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 21:06:30,682        INFO         client.py                 Установлено соединение с сервером.Принят ответ от сервера 200 : OK
2023-06-18 21:06:30,683        DEBUG        client.py                 Запущены процессы
2023-06-18 21:07:16,047        DEBUG        client.py                 Сформирован словарь сообщения: {'action': 'message', 'from': 'test_1', 'to': 'test_2', 'time': 1687111636.0479417, 'mess_text': 'Hi friends'}
2023-06-18 21:07:16,051        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=332, family=2, type=1, proto=0, laddr=('127.0.0.1', 51305), raddr=('127.0.0.1', 8079)>, {'action': 'message', 'from': 'test_1', 'to': 'test_2', 'time': 1687111636.0479417, 'mess_text': 'Hi friends'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции create_message
2023-06-18 21:07:16,051        INFO         client.py                 Отправлено сообщение для пользователя test_2
2023-06-18 21:07:16,448        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=320, family=2, type=1, proto=0, laddr=('127.0.0.1', 51306), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 21:07:16,449        INFO         client.py                 Получено сообщение от пользователя test_1:
Hi friends
2023-06-18 21:08:01,384        DEBUG        client.py                 Сформирован словарь сообщения: {'action': 'message', 'from': 'test_2', 'to': 'test_3', 'time': 1687111681.3847148, 'mess_text': 'Hello'}
2023-06-18 21:08:01,385        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=320, family=2, type=1, proto=0, laddr=('127.0.0.1', 51306), raddr=('127.0.0.1', 8079)>, {'action': 'message', 'from': 'test_2', 'to': 'test_3', 'time': 1687111681.3847148, 'mess_text': 'Hello'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции create_message
2023-06-18 21:08:01,385        INFO         client.py                 Отправлено сообщение для пользователя test_3
2023-06-18 21:08:01,712        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=396, family=2, type=1, proto=0, laddr=('127.0.0.1', 51307), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 21:08:01,713        INFO         client.py                 Получено сообщение от пользователя test_2:
Hello
2023-06-18 21:08:51,400        DEBUG        client.py                 Сформирован словарь сообщения: {'action': 'message', 'from': 'test_3', 'to': 'test_1', 'time': 1687111731.4005957, 'mess_text': 'goodbye'}
2023-06-18 21:08:51,401        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=396, family=2, type=1, proto=0, laddr=('127.0.0.1', 51307), raddr=('127.0.0.1', 8079)>, {'action': 'message', 'from': 'test_3', 'to': 'test_1', 'time': 1687111731.4005957, 'mess_text': 'goodbye'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции create_message
2023-06-18 21:08:51,402        INFO         client.py                 Отправлено сообщение для пользователя test_1
2023-06-18 21:08:51,565        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=332, family=2, type=1, proto=0, laddr=('127.0.0.1', 51305), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 21:08:51,565        INFO         client.py                 Получено сообщение от пользователя test_3:
goodbye
2023-06-18 21:08:59,681        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=396, family=2, type=1, proto=0, laddr=('127.0.0.1', 51307), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687111739.6808212, 'account_name': 'test_3', 'mess_text': 'Пользователь test_3 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 21:08:59,682        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 21:09:00,174        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 21:09:06,705        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=320, family=2, type=1, proto=0, laddr=('127.0.0.1', 51306), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687111746.703971, 'account_name': 'test_2', 'mess_text': 'Пользователь test_2 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 21:09:06,706        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 21:09:06,792        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 21:09:13,457        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=332, family=2, type=1, proto=0, laddr=('127.0.0.1', 51305), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687111753.456341, 'account_name': 'test_1', 'mess_text': 'Пользователь test_1 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 21:09:13,458        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 21:09:13,916        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 21:51:26,500        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_1
2023-06-18 21:51:26,511        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_2
2023-06-18 21:51:26,548        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_3
2023-06-18 21:51:28,552        CRITICAL     client.py                 Не удалось подключиться к серверу 127.0.0.1:8079, конечный компьютер отверг запрос на подключение.
2023-06-18 21:51:28,599        CRITICAL     client.py                 Не удалось подключиться к серверу 127.0.0.1:8079, конечный компьютер отверг запрос на подключение.
2023-06-18 21:56:21,855        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_1
2023-06-18 21:56:21,856        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_1
2023-06-18 21:56:21,861        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_2
2023-06-18 21:56:21,862        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_2
2023-06-18 21:56:21,880        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_1',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:21,881        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=408, family=2, type=1, proto=0, laddr=('127.0.0.1', 52604), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687114581.8568363, 'user': {'account_name': 'test_1'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:21,885        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_2',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:21,886        INFO         client.py                 Запущен клиент с параметрами: адрес сервера: 127.0.0.1, порт: 8079, имя пользователя: test_3
2023-06-18 21:56:21,886        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=308, family=2, type=1, proto=0, laddr=('127.0.0.1', 52605), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687114581.8628204, 'user': {'account_name': 'test_2'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:21,887        DEBUG        client.py                 Сформировано presence сообщение для пользователя test_3
2023-06-18 21:56:21,903        DEBUG        client.py                 Была вызвана функция create_presence c параметрами ('test_3',), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:21,904        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=440, family=2, type=1, proto=0, laddr=('127.0.0.1', 52606), raddr=('127.0.0.1', 8079)>, {'action': 'presence', 'time': 1687114581.8868074, 'user': {'account_name': 'test_3'}}), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:21,906        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=408, family=2, type=1, proto=0, laddr=('127.0.0.1', 52604), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:21,906        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 21:56:21,907        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:21,907        INFO         client.py                 Установлено соединение с сервером.Принят ответ от сервера 200 : OK
2023-06-18 21:56:21,909        DEBUG        client.py                 Запущены процессы
2023-06-18 21:56:21,909        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=308, family=2, type=1, proto=0, laddr=('127.0.0.1', 52605), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:21,910        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 21:56:21,910        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:21,911        INFO         client.py                 Установлено соединение с сервером.Принят ответ от сервера 200 : OK
2023-06-18 21:56:21,912        DEBUG        client.py                 Запущены процессы
2023-06-18 21:56:22,421        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=440, family=2, type=1, proto=0, laddr=('127.0.0.1', 52606), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:22,421        DEBUG        client.py                 Получено сообщение от сервера: {'response': 200}
2023-06-18 21:56:22,422        DEBUG        client.py                 Была вызвана функция process_ans c параметрами ({'response': 200},), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-06-18 21:56:22,422        INFO         client.py                 Установлено соединение с сервером.Принят ответ от сервера 200 : OK
2023-06-18 21:56:22,424        DEBUG        client.py                 Запущены процессы
2023-06-18 21:57:18,409        DEBUG        client.py                 Сформирован словарь сообщения: {'action': 'message', 'from': 'test_2', 'to': 'test_1', 'time': 1687114638.4094841, 'mess_text': 'goodmorning'}
2023-06-18 21:57:18,411        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=308, family=2, type=1, proto=0, laddr=('127.0.0.1', 52605), raddr=('127.0.0.1', 8079)>, {'action': 'message', 'from': 'test_2', 'to': 'test_1', 'time': 1687114638.4094841, 'mess_text': 'goodmorning'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции create_message
2023-06-18 21:57:18,411        INFO         client.py                 Отправлено сообщение для пользователя test_1
2023-06-18 21:57:18,458        DEBUG        client.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=408, family=2, type=1, proto=0, laddr=('127.0.0.1', 52604), raddr=('127.0.0.1', 8079)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 21:57:18,458        INFO         client.py                 Получено сообщение от пользователя test_2:
goodmorning
2023-06-18 21:57:24,002        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=308, family=2, type=1, proto=0, laddr=('127.0.0.1', 52605), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687114644.0007727, 'account_name': 'test_2', 'mess_text': 'Пользователь test_2 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 21:57:24,002        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 21:57:24,054        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 21:57:29,770        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=408, family=2, type=1, proto=0, laddr=('127.0.0.1', 52604), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687114649.7693386, 'account_name': 'test_1', 'mess_text': 'Пользователь test_1 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 21:57:29,771        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 21:57:30,174        CRITICAL     client.py                 Потеряно соединение с сервером.
2023-06-18 21:57:34,675        DEBUG        client.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=440, family=2, type=1, proto=0, laddr=('127.0.0.1', 52606), raddr=('127.0.0.1', 8079)>, {'action': 'exit', 'time': 1687114654.6736925, 'account_name': 'test_3', 'mess_text': 'Пользователь test_3 вышел из чата.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-06-18 21:57:34,675        INFO         client.py                 Завершение работы по команде пользователя.
2023-06-18 21:57:34,763        CRITICAL     client.py                 Потеряно соединение с сервером.
